#!/bin/bash
#SBATCH --job-name=kofamscan
#SBATCH --cpus-per-task=8
#SBATCH --mem=16G
#SBATCH --time=04:00:00
#SBATCH --partition=standard
#SBATCH --account=hammert_lab
#SBATCH --output=/dfs10/hammert-lab/nvillabo/Ch2/work_meta/logs/kofamscan/kofamscan_%A_%a.out
#SBATCH --error=/dfs10/hammert-lab/nvillabo/Ch2/work_meta/logs/kofamscan/kofamscan_%A_%a.err

# ============================================================
# 8b_kofamscan.sh
# Author: Nickole Villabona
# KEGG functional annotation with KofamScan — job array
# ============================================================
# Annotates genes in each MAG with KEGG Orthology (KO) numbers
# using HMM profiles. Reuses protein predictions (uniInput.faa)
# generated by dbCAN2/Prodigal in the binning step.
#
# Input:  /work_meta/08_annotation/dbcan_all/{MAG}/uniInput.faa
#         /dfs10/hammert-lab/nvillabo/databases/kofamscan/
# Output: /work_meta/08_annotation/kofamscan/{MAG}/ko_mapper.txt
#         (gene -> KO assignments, threshold-passing hits only)
#
# Tools: KofamScan (exec_annotation)
#
# Prereq: run 8b_kofamscan_setup.sh once before submitting.
# Usage:  sbatch --array=1-121 8b_kofamscan.sh
# Runtime: ~1-3 hours per MAG
# ============================================================

# ======== BASE PATHS ========
DBCAN_DIR=/dfs10/hammert-lab/nvillabo/Ch2/work_meta/08_annotation/dbcan_all
OUT_BASE=/dfs10/hammert-lab/nvillabo/Ch2/work_meta/08_annotation/kofamscan
DB_DIR=/dfs10/hammert-lab/nvillabo/databases/kofamscan
MAG_LIST=/dfs10/hammert-lab/nvillabo/Ch2/work_meta/08_annotation/kofamscan_mag_list.txt
LOG_DIR=/dfs10/hammert-lab/nvillabo/Ch2/work_meta/logs/kofamscan

mkdir -p "$OUT_BASE" "$LOG_DIR"

# ======== LOAD ENVIRONMENT ========
module purge
module load mamba/24.3.0
source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate /dfs10/hammert-lab/nvillabo/envs/kofamscan_env

ENV_PATH=/dfs10/hammert-lab/nvillabo/envs/kofamscan_env
RUBY="${ENV_PATH}/bin/ruby"
EXEC_ANNOTATION="${ENV_PATH}/bin/exec_annotation"

# Ruby 4.0 on DFS nodes has intermittent gemspec load failures due to NFS cold
# cache. Warm the cache first, then retry up to 3 times with a delay.
find "${ENV_PATH}/lib/ruby" -name '*.gemspec' > /dev/null 2>&1 || true

echo "[$(date)] Using environment: kofamscan_env"
for attempt in 1 2 3; do
    if "$RUBY" "$EXEC_ANNOTATION" --version 2>/dev/null; then
        break
    fi
    echo "[$(date)] Ruby startup failed (attempt ${attempt}/3) — NFS cache miss, retrying in 20s..."
    sleep 20
    find "${ENV_PATH}/lib/ruby" -name '*.gemspec' > /dev/null 2>&1 || true
    if [ "$attempt" -eq 3 ]; then
        echo "[$(date)] ERROR: exec_annotation not found after 3 attempts"
        exit 1
    fi
done

# ======== RESOLVE THIS TASK'S MAG ========
MAG=$(sed -n "${SLURM_ARRAY_TASK_ID}p" "$MAG_LIST")
INPUT_FAA="${DBCAN_DIR}/${MAG}/uniInput.faa"
MAG_OUT="${OUT_BASE}/${MAG}"
TMP_DIR="${MAG_OUT}/tmp"

echo "[$(date)] MAG: $MAG (task ${SLURM_ARRAY_TASK_ID})"

# ======== VALIDATE INPUTS ========
[[ -f "$MAG_LIST" ]]          || { echo "[$(date)] ERROR: MAG list not found: $MAG_LIST — run setup script first"; exit 1; }
[[ -f "$INPUT_FAA" ]]         || { echo "[$(date)] ERROR: $INPUT_FAA not found"; exit 1; }
[[ -f "${DB_DIR}/ko_list" ]]  || { echo "[$(date)] ERROR: ko_list missing — run 8b_kofamscan_setup.sh first"; exit 1; }
[[ -d "${DB_DIR}/profiles" ]] || { echo "[$(date)] ERROR: profiles dir missing — run 8b_kofamscan_setup.sh first"; exit 1; }

mkdir -p "$MAG_OUT" "$TMP_DIR"

# ======== RUN KOFAMSCAN ========
"$RUBY" "$EXEC_ANNOTATION" \
  --cpu "$SLURM_CPUS_PER_TASK" \
  --ko-list  "${DB_DIR}/ko_list" \
  --profile  "${DB_DIR}/profiles" \
  --tmp-dir  "$TMP_DIR" \
  -f mapper \
  -o "${MAG_OUT}/ko_mapper.txt" \
  "$INPUT_FAA"

rm -rf "$TMP_DIR"

echo "[$(date)] Done — $(wc -l < "${MAG_OUT}/ko_mapper.txt") KO assignments written for $MAG"
echo "[$(date)] ==== End of KofamScan for $MAG ===="
